Repository opitzconsulting/ansible-oracle, pull requests merged in 2022-07, with the labels that each got.

#96 orahost: added options to host_fs_layout
  roles/orahost/tasks/main.yml
Labels: enhancement

#95 oracle_profile: Bugfix python2+3
  library/oracle_profile
Labels: bug

#93 bugfix hardcoded /home/oracle - use oracle_user_home
  roles/oradb-create/templates/dotprofile-db.j2
  roles/oradb-manage-db/defaults/main.yml
  roles/oradb-manage-db/tasks/manage-db.yml
  roles/oradb-manage-db/templates/dotprofile-db.j2
  roles/orahost/tasks/main.yml
  roles/oraswdb-install/tasks/install-home-db.yml
  roles/oraswdb-install/templates/dotprofile-home.j2
Labels: enhancement

#92 bugfix: gold image copy path
  roles/oraswdb-install/tasks/install-home-db.yml
Labels: bug

#81 update password really only when needed with update_password=always + support for password_hash
  library/oracle_user
  roles/oradb-manage-users/tasks/main.yml
Labels: bug

#97 Breaking Change: removed deprecated roles
  roles/oraasm-createdg/defaults/main.yml
  roles/oraasm-createdg/tasks/main.yml
  roles/oraasm-createdg/templates/asmca-createdg.sh.j2
  roles/oradb-create/defaults/main.yml
  roles/oradb-create/tasks/listener.yml
  roles/oradb-create/tasks/main.yml
  roles/oradb-create/templates/dbca-create-db.rsp.11.2.0.3.j2
  roles/oradb-create/templates/dbca-create-db.rsp.11.2.0.4.j2
  roles/oradb-create/templates/dbca-create-db.rsp.12.1.0.1.j2
  roles/oradb-create/templates/dbca-create-db.rsp.12.1.0.2.j2
  roles/oradb-create/templates/dbca-create-db.rsp.12.2.0.1.j2
  roles/oradb-create/templates/dotprofile-db.j2
  roles/oradb-create/templates/netca.rsp.11.2.0.3.j2
  roles/oradb-create/templates/netca.rsp.11.2.0.4.j2
  roles/oradb-create/templates/netca.rsp.12.1.0.1.j2
  roles/oradb-create/templates/netca.rsp.12.1.0.2.j2
  roles/oradb-create/templates/netca.rsp.12.2.0.1.j2
  roles/oradb-delete/defaults/main.yml
  roles/oradb-delete/tasks/main.yml
  roles/oradb-failover/defaults/main.yml
  roles/oradb-failover/tasks/main.yml
  roles/oradb-failover/templates/act_db.pl.j2
  roles/oradb-failover/templates/attributes.txt.j2
  roles/oradb-failover/templates/shutdown-db.sh.j2
  roles/oraswgi-clone/clone.sh
  roles/oraswgi-clone/files/grid-all.rsp
  roles/oraswgi-clone/tasks/main.yml
  roles/oraswgi-clone/templates/clone.sh.j2
  roles/oraswgi-clone/templates/dotprofile-db.j2
  roles/oraswgi-clone/templates/dotprofile-gi.j2
  roles/oraswgi-clone/templates/dotprofile.j2
  roles/oraswgi-clone/templates/listener.ora.j2
  roles/oraswgi-clone/templates/tnsnames.ora.j2
  roles/oraswgi-clone/vars/main.yml
  roles/oraswracdb-clone/clone.sh
  roles/oraswracdb-clone/files/grid-all.rsp
  roles/oraswracdb-clone/tasks/main.yml
  roles/oraswracdb-clone/templates/clone.sh.j2
  roles/oraswracdb-clone/templates/dotprofile-db.j2
  roles/oraswracdb-clone/templates/dotprofile-gi.j2
  roles/oraswracdb-clone/templates/dotprofile.j2
  roles/oraswracdb-clone/templates/listener.ora.j2
  roles/oraswracdb-clone/templates/tnsnames.ora.j2
Labels: enhancement

#107 fix: optional uid gid password
  changelogs/fragments/107-optional_uid_gid_passwd.yaml
  roles/orahost/tasks/main.yml
Labels: enhancement

#108 bugfix: host_fs_layout needed disk even if configure_host_disks==false
  changelogs/fragments/108-host_fs_layout.yaml
  roles/orahost/tasks/main.yml
Labels: enhancement

#110 changelog: pass container and container_data parameters to modules
  changelogs/fragments/109-pass-container-header.yaml
Labels: documentation
